### ISSUE TITLE
Remove build directory from git

### ISSUE THREAD

**Issue by internettrans** [ariesjia/single-spa-riot#2]
Nice work on this project! One suggestion I would make is to remove the [build directory](https://github.com/ariesjia/single-spa-riot/tree/af9e59fafb1a81c27e514244e57570d0391c796e/build) from version control altogether. This makes it so that pull requests are easier to review since they won't have the changes to the build directory in them. And also that you don't have to explain to contributors that the build directory shouldn't be committed and pushed during PRs.

To do this, you'll also have to make sure the build directory is still published to npm. You can use the [package.json `files` property](https://docs.npmjs.com/files/package.json#files) to accomplish this.

**Comment by ariesjia** [comment]
Thanks,
The [build directory](https://github.com/ariesjia/single-spa-riot/tree/af9e59fafb1a81c27e514244e57570d0391c796e/build) is mainly for the compile typescript and compress the bundle file, It' s all the rollup config code, and I use the [travis-ci](https://travis-ci.org/ariesjia/single-spa-riot) to publish to npm.   So the code should be pushed to git, otherwise travis ci can't get the code to execute.

**Comment by internettrans** [comment]
fair enough 👍 -- the alternative would be to run typescript and bundling steps in the travis build such that the build directory is generated on the travis server instead of already present in github. However, this comes down to personal preference and as the owner of the repo it's totally your call. I'll close this issue.
